<?php

namespace Database\Seeders;

use App\Models\Breed;
use App\Models\Species;
use Illuminate\Database\Seeder;

class SpeciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $speciesData = [
            [
                'name' => 'Dog',
                'slug' => 'dog',
                'description' => 'Man\'s best friend and loyal companion',
                'breeds' => [
                    'Affenpinscher',
                    'Afghan Hound',
                    'Airedale Terrier',
                    'Akita',
                    'Alaskan Malamute',
                    'American Bulldog',
                    'American Eskimo Dog',
                    'American Foxhound',
                    'American Pit Bull Terrier',
                    'American Staffordshire Terrier',
                    'American Water Spaniel',
                    'Anatolian Shepherd Dog',
                    'Australian Cattle Dog',
                    'Australian Shepherd',
                    'Australian Terrier',
                    'Basenji',
                    'Basset Hound',
                    'Beagle',
                    'Bearded Collie',
                    'Beauceron',
                    'Bedlington Terrier',
                    'Belgian Malinois',
                    'Belgian Sheepdog',
                    'Belgian Tervuren',
                    'Bernese Mountain Dog',
                    'Bichon Frise',
                    'Bloodhound',
                    'Blue Heeler',
                    'Border Collie',
                    'Border Terrier',
                    'Borzoi',
                    'Boston Terrier',
                    'Bouvier des Flandres',
                    'Boxer',
                    'Briard',
                    'Brittany',
                    'Brussels Griffon',
                    'Bull Terrier',
                    'Bulldog',
                    'Bullmastiff',
                    'Cairn Terrier',
                    'Canaan Dog',
                    'Cane Corso',
                    'Cardigan Welsh Corgi',
                    'Cavalier King Charles Spaniel',
                    'Chesapeake Bay Retriever',
                    'Chihuahua',
                    'Chinese Crested',
                    'Chinese Shar-Pei',
                    'Chow Chow',
                    'Clumber Spaniel',
                    'Cocker Spaniel',
                    'Collie',
                    'Coonhound',
                    'Corgi',
                    'Coton de Tulear',
                    'Curly-Coated Retriever',
                    'Dachshund',
                    'Dalmatian',
                    'Dandie Dinmont Terrier',
                    'Doberman Pinscher',
                    'Dogo Argentino',
                    'Dogue de Bordeaux',
                    'English Bulldog',
                    'English Cocker Spaniel',
                    'English Foxhound',
                    'English Setter',
                    'English Springer Spaniel',
                    'English Toy Spaniel',
                    'Field Spaniel',
                    'Finnish Spitz',
                    'Flat-Coated Retriever',
                    'Fox Terrier',
                    'French Bulldog',
                    'German Pinscher',
                    'German Shepherd',
                    'German Shorthaired Pointer',
                    'German Wirehaired Pointer',
                    'Giant Schnauzer',
                    'Glen of Imaal Terrier',
                    'Golden Retriever',
                    'Gordon Setter',
                    'Great Dane',
                    'Great Pyrenees',
                    'Greater Swiss Mountain Dog',
                    'Greyhound',
                    'Harrier',
                    'Havanese',
                    'Ibizan Hound',
                    'Icelandic Sheepdog',
                    'Irish Setter',
                    'Irish Terrier',
                    'Irish Water Spaniel',
                    'Irish Wolfhound',
                    'Italian Greyhound',
                    'Jack Russell Terrier',
                    'Japanese Chin',
                    'Keeshond',
                    'Kerry Blue Terrier',
                    'Komondor',
                    'Kuvasz',
                    'Labrador Retriever',
                    'Lakeland Terrier',
                    'Leonberger',
                    'Lhasa Apso',
                    'Lowchen',
                    'Maltese',
                    'Manchester Terrier',
                    'Mastiff',
                    'Miniature Bull Terrier',
                    'Miniature Pinscher',
                    'Miniature Schnauzer',
                    'Neapolitan Mastiff',
                    'Newfoundland',
                    'Norfolk Terrier',
                    'Norwegian Elkhound',
                    'Norwich Terrier',
                    'Nova Scotia Duck Tolling Retriever',
                    'Old English Sheepdog',
                    'Otterhound',
                    'Papillon',
                    'Parson Russell Terrier',
                    'Pekingese',
                    'Pembroke Welsh Corgi',
                    'Petit Basset Griffon Vendeen',
                    'Pharaoh Hound',
                    'Plott',
                    'Pointer',
                    'Polish Lowland Sheepdog',
                    'Pomeranian',
                    'Poodle',
                    'Portuguese Water Dog',
                    'Pug',
                    'Puli',
                    'Pyrenean Shepherd',
                    'Rat Terrier',
                    'Redbone Coonhound',
                    'Rhodesian Ridgeback',
                    'Rottweiler',
                    'Saint Bernard',
                    'Saluki',
                    'Samoyed',
                    'Schipperke',
                    'Scottish Deerhound',
                    'Scottish Terrier',
                    'Sealyham Terrier',
                    'Shetland Sheepdog',
                    'Shiba Inu',
                    'Shih Tzu',
                    'Siberian Husky',
                    'Silky Terrier',
                    'Skye Terrier',
                    'Smooth Fox Terrier',
                    'Soft Coated Wheaten Terrier',
                    'Spanish Water Dog',
                    'Spinone Italiano',
                    'Staffordshire Bull Terrier',
                    'Standard Schnauzer',
                    'Sussex Spaniel',
                    'Swedish Vallhund',
                    'Tibetan Mastiff',
                    'Tibetan Spaniel',
                    'Tibetan Terrier',
                    'Toy Fox Terrier',
                    'Treeing Walker Coonhound',
                    'Vizsla',
                    'Weimaraner',
                    'Welsh Springer Spaniel',
                    'Welsh Terrier',
                    'West Highland White Terrier',
                    'Whippet',
                    'Wire Fox Terrier',
                    'Wirehaired Pointing Griffon',
                    'Xoloitzcuintli',
                    'Yorkshire Terrier',
                    'Mixed Breed',
                ],
            ],
            [
                'name' => 'Cat',
                'slug' => 'cat',
                'description' => 'Independent and affectionate feline companions',
                'breeds' => [
                    'Abyssinian',
                    'Aegean',
                    'American Bobtail',
                    'American Curl',
                    'American Shorthair',
                    'American Wirehair',
                    'Arabian Mau',
                    'Australian Mist',
                    'Balinese',
                    'Bambino',
                    'Bengal',
                    'Birman',
                    'Bombay',
                    'British Longhair',
                    'British Shorthair',
                    'Burmese',
                    'Burmilla',
                    'California Spangled',
                    'Chantilly-Tiffany',
                    'Chartreux',
                    'Chausie',
                    'Colorpoint Shorthair',
                    'Cornish Rex',
                    'Cymric',
                    'Cyprus',
                    'Devon Rex',
                    'Donskoy',
                    'Domestic Longhair',
                    'Domestic Shorthair',
                    'Dragon Li',
                    'Egyptian Mau',
                    'European Shorthair',
                    'Exotic Shorthair',
                    'Foldex',
                    'German Rex',
                    'Havana Brown',
                    'Highlander',
                    'Himalayan',
                    'Japanese Bobtail',
                    'Javanese',
                    'Khao Manee',
                    'Korat',
                    'Korean Bobtail',
                    'Kurilian Bobtail',
                    'LaPerm',
                    'Lykoi',
                    'Maine Coon',
                    'Manx',
                    'Mekong Bobtail',
                    'Minskin',
                    'Munchkin',
                    'Nebelung',
                    'Norwegian Forest Cat',
                    'Ocicat',
                    'Ojos Azules',
                    'Oregon Rex',
                    'Oriental Bicolor',
                    'Oriental Longhair',
                    'Oriental Shorthair',
                    'Persian',
                    'Peterbald',
                    'Pixie-bob',
                    'Ragamuffin',
                    'Ragdoll',
                    'Russian Blue',
                    'Russian White',
                    'Sam Sawet',
                    'Savannah',
                    'Scottish Fold',
                    'Selkirk Rex',
                    'Serengeti',
                    'Siamese',
                    'Siberian',
                    'Singapura',
                    'Snowshoe',
                    'Sokoke',
                    'Somali',
                    'Sphynx',
                    'Suphalak',
                    'Thai',
                    'Tonkinese',
                    'Toyger',
                    'Turkish Angora',
                    'Turkish Van',
                    'Ukrainian Levkoy',
                    'York Chocolate',
                    'Mixed Breed',
                ],
            ],
            [
                'name' => 'Rabbit',
                'slug' => 'rabbit',
                'description' => 'Gentle and social small pets',
                'breeds' => [
                    'Holland Lop',
                    'Netherland Dwarf',
                    'Mini Rex',
                    'Lionhead',
                    'Flemish Giant',
                    'Dutch',
                    'Mixed Breed',
                ],
            ],
            [
                'name' => 'Bird',
                'slug' => 'bird',
                'description' => 'Colorful and intelligent avian companions',
                'breeds' => [
                    'Parakeet',
                    'Cockatiel',
                    'Canary',
                    'Finch',
                    'Cockatoo',
                    'Parrot',
                ],
            ],
            [
                'name' => 'Guinea Pig',
                'slug' => 'guinea-pig',
                'description' => 'Social and vocal small pets',
                'breeds' => [
                    'American',
                    'Abyssinian',
                    'Peruvian',
                    'Silkie',
                    'Texel',
                ],
            ],
        ];

        foreach ($speciesData as $speciesInfo) {
            $breeds = $speciesInfo['breeds'];
            unset($speciesInfo['breeds']);

            $species = Species::create($speciesInfo);

            foreach ($breeds as $breedName) {
                Breed::create([
                    'species_id' => $species->id,
                    'name' => $breedName,
                    'slug' => \Illuminate\Support\Str::slug($breedName),
                ]);
            }
        }
    }
}
