<?php

namespace App\Filament\Resources\Species\Schemas;

use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;

class SpeciesForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('name')
                    ->required()
                    ->live(onBlur: true)
                    ->afterStateUpdated(fn ($state, callable $set) => $set('slug', \Illuminate\Support\Str::slug($state))),
                TextInput::make('slug')
                    ->required()
                    ->unique(ignoreRecord: true),
                Textarea::make('description')
                    ->columnSpanFull(),
                Select::make('icon')
                    ->label('Icon')
                    ->options(self::getAllHeroicons())
                    ->searchable()
                    ->placeholder('Select an icon')
                    ->helperText('Choose an icon to represent this species'),
            ]);
    }

    protected static function getAllHeroicons(): array
    {
        return [
            Heroicon::OutlinedAcademicCap->value => 'Academic Cap',
            Heroicon::OutlinedAdjustmentsHorizontal->value => 'Adjustments Horizontal',
            Heroicon::OutlinedAdjustmentsVertical->value => 'Adjustments Vertical',
            Heroicon::OutlinedArchiveBox->value => 'Archive Box',
            Heroicon::OutlinedArchiveBoxArrowDown->value => 'Archive Box Arrow Down',
            Heroicon::OutlinedArchiveBoxXMark->value => 'Archive Box X Mark',
            Heroicon::OutlinedArrowDown->value => 'Arrow Down',
            Heroicon::OutlinedArrowDownCircle->value => 'Arrow Down Circle',
            Heroicon::OutlinedArrowDownLeft->value => 'Arrow Down Left',
            Heroicon::OutlinedArrowDownOnSquare->value => 'Arrow Down On Square',
            Heroicon::OutlinedArrowDownOnSquareStack->value => 'Arrow Down On Square Stack',
            Heroicon::OutlinedArrowDownRight->value => 'Arrow Down Right',
            Heroicon::OutlinedArrowDownTray->value => 'Arrow Down Tray',
            Heroicon::OutlinedArrowLeft->value => 'Arrow Left',
            Heroicon::OutlinedArrowLeftCircle->value => 'Arrow Left Circle',
            Heroicon::OutlinedArrowLeftEndOnRectangle->value => 'Arrow Left End On Rectangle',
            Heroicon::OutlinedArrowLeftOnRectangle->value => 'Arrow Left On Rectangle',
            Heroicon::OutlinedArrowLeftStartOnRectangle->value => 'Arrow Left Start On Rectangle',
            Heroicon::OutlinedArrowLongDown->value => 'Arrow Long Down',
            Heroicon::OutlinedArrowLongLeft->value => 'Arrow Long Left',
            Heroicon::OutlinedArrowLongRight->value => 'Arrow Long Right',
            Heroicon::OutlinedArrowLongUp->value => 'Arrow Long Up',
            Heroicon::OutlinedArrowPath->value => 'Arrow Path',
            Heroicon::OutlinedArrowPathRoundedSquare->value => 'Arrow Path Rounded Square',
            Heroicon::OutlinedArrowRight->value => 'Arrow Right',
            Heroicon::OutlinedArrowRightCircle->value => 'Arrow Right Circle',
            Heroicon::OutlinedArrowRightEndOnRectangle->value => 'Arrow Right End On Rectangle',
            Heroicon::OutlinedArrowRightOnRectangle->value => 'Arrow Right On Rectangle',
            Heroicon::OutlinedArrowRightStartOnRectangle->value => 'Arrow Right Start On Rectangle',
            Heroicon::OutlinedArrowSmallDown->value => 'Arrow Small Down',
            Heroicon::OutlinedArrowSmallLeft->value => 'Arrow Small Left',
            Heroicon::OutlinedArrowSmallRight->value => 'Arrow Small Right',
            Heroicon::OutlinedArrowSmallUp->value => 'Arrow Small Up',
            Heroicon::OutlinedArrowTopRightOnSquare->value => 'Arrow Top Right On Square',
            Heroicon::OutlinedArrowTrendingDown->value => 'Arrow Trending Down',
            Heroicon::OutlinedArrowTrendingUp->value => 'Arrow Trending Up',
            Heroicon::OutlinedArrowTurnDownLeft->value => 'Arrow Turn Down Left',
            Heroicon::OutlinedArrowTurnDownRight->value => 'Arrow Turn Down Right',
            Heroicon::OutlinedArrowTurnLeftDown->value => 'Arrow Turn Left Down',
            Heroicon::OutlinedArrowTurnLeftUp->value => 'Arrow Turn Left Up',
            Heroicon::OutlinedArrowTurnRightDown->value => 'Arrow Turn Right Down',
            Heroicon::OutlinedArrowTurnRightUp->value => 'Arrow Turn Right Up',
            Heroicon::OutlinedArrowTurnUpLeft->value => 'Arrow Turn Up Left',
            Heroicon::OutlinedArrowTurnUpRight->value => 'Arrow Turn Up Right',
            Heroicon::OutlinedArrowUp->value => 'Arrow Up',
            Heroicon::OutlinedArrowUpCircle->value => 'Arrow Up Circle',
            Heroicon::OutlinedArrowUpLeft->value => 'Arrow Up Left',
            Heroicon::OutlinedArrowUpOnSquare->value => 'Arrow Up On Square',
            Heroicon::OutlinedArrowUpOnSquareStack->value => 'Arrow Up On Square Stack',
            Heroicon::OutlinedArrowUpRight->value => 'Arrow Up Right',
            Heroicon::OutlinedArrowUpTray->value => 'Arrow Up Tray',
            Heroicon::OutlinedArrowUturnDown->value => 'Arrow U-turn Down',
            Heroicon::OutlinedArrowUturnLeft->value => 'Arrow U-turn Left',
            Heroicon::OutlinedArrowUturnRight->value => 'Arrow U-turn Right',
            Heroicon::OutlinedArrowUturnUp->value => 'Arrow U-turn Up',
            Heroicon::OutlinedArrowsPointingIn->value => 'Arrows Pointing In',
            Heroicon::OutlinedArrowsPointingOut->value => 'Arrows Pointing Out',
            Heroicon::OutlinedArrowsRightLeft->value => 'Arrows Right Left',
            Heroicon::OutlinedArrowsUpDown->value => 'Arrows Up Down',
            Heroicon::OutlinedAtSymbol->value => 'At Symbol',
            Heroicon::OutlinedBackspace->value => 'Backspace',
            Heroicon::OutlinedBackward->value => 'Backward',
            Heroicon::OutlinedBanknotes->value => 'Banknotes',
            Heroicon::OutlinedBars2->value => 'Bars 2',
            Heroicon::OutlinedBars3->value => 'Bars 3',
            Heroicon::OutlinedBars3BottomLeft->value => 'Bars 3 Bottom Left',
            Heroicon::OutlinedBars3BottomRight->value => 'Bars 3 Bottom Right',
            Heroicon::OutlinedBars3CenterLeft->value => 'Bars 3 Center Left',
            Heroicon::OutlinedBars4->value => 'Bars 4',
            Heroicon::OutlinedBarsArrowDown->value => 'Bars Arrow Down',
            Heroicon::OutlinedBarsArrowUp->value => 'Bars Arrow Up',
            Heroicon::OutlinedBattery0->value => 'Battery 0%',
            Heroicon::OutlinedBattery50->value => 'Battery 50%',
            Heroicon::OutlinedBattery100->value => 'Battery 100%',
            Heroicon::OutlinedBeaker->value => 'Beaker',
            Heroicon::OutlinedBell->value => 'Bell',
            Heroicon::OutlinedBellAlert->value => 'Bell Alert',
            Heroicon::OutlinedBellSlash->value => 'Bell Slash',
            Heroicon::OutlinedBellSnooze->value => 'Bell Snooze',
            Heroicon::OutlinedBold->value => 'Bold',
            Heroicon::OutlinedBolt->value => 'Bolt',
            Heroicon::OutlinedBoltSlash->value => 'Bolt Slash',
            Heroicon::OutlinedBookOpen->value => 'Book Open',
            Heroicon::OutlinedBookmark->value => 'Bookmark',
            Heroicon::OutlinedBookmarkSlash->value => 'Bookmark Slash',
            Heroicon::OutlinedBookmarkSquare->value => 'Bookmark Square',
            Heroicon::OutlinedBriefcase->value => 'Briefcase',
            Heroicon::OutlinedBugAnt->value => 'Bug Ant',
            Heroicon::OutlinedBuildingLibrary->value => 'Building Library',
            Heroicon::OutlinedBuildingOffice->value => 'Building Office',
            Heroicon::OutlinedBuildingOffice2->value => 'Building Office 2',
            Heroicon::OutlinedBuildingStorefront->value => 'Building Storefront',
            Heroicon::OutlinedCake->value => 'Cake',
            Heroicon::OutlinedCalculator->value => 'Calculator',
            Heroicon::OutlinedCalendar->value => 'Calendar',
            Heroicon::OutlinedCalendarDateRange->value => 'Calendar Date Range',
            Heroicon::OutlinedCalendarDays->value => 'Calendar Days',
            Heroicon::OutlinedCamera->value => 'Camera',
            Heroicon::OutlinedChartBar->value => 'Chart Bar',
            Heroicon::OutlinedChartBarSquare->value => 'Chart Bar Square',
            Heroicon::OutlinedChartPie->value => 'Chart Pie',
            Heroicon::OutlinedChatBubbleBottomCenter->value => 'Chat Bubble Bottom Center',
            Heroicon::OutlinedChatBubbleBottomCenterText->value => 'Chat Bubble Bottom Center Text',
            Heroicon::OutlinedChatBubbleLeft->value => 'Chat Bubble Left',
            Heroicon::OutlinedChatBubbleLeftEllipsis->value => 'Chat Bubble Left Ellipsis',
            Heroicon::OutlinedChatBubbleLeftRight->value => 'Chat Bubble Left Right',
            Heroicon::OutlinedChatBubbleOvalLeft->value => 'Chat Bubble Oval Left',
            Heroicon::OutlinedChatBubbleOvalLeftEllipsis->value => 'Chat Bubble Oval Left Ellipsis',
            Heroicon::OutlinedCheck->value => 'Check',
            Heroicon::OutlinedCheckBadge->value => 'Check Badge',
            Heroicon::OutlinedCheckCircle->value => 'Check Circle',
            Heroicon::OutlinedChevronDoubleDown->value => 'Chevron Double Down',
            Heroicon::OutlinedChevronDoubleLeft->value => 'Chevron Double Left',
            Heroicon::OutlinedChevronDoubleRight->value => 'Chevron Double Right',
            Heroicon::OutlinedChevronDoubleUp->value => 'Chevron Double Up',
            Heroicon::OutlinedChevronDown->value => 'Chevron Down',
            Heroicon::OutlinedChevronLeft->value => 'Chevron Left',
            Heroicon::OutlinedChevronRight->value => 'Chevron Right',
            Heroicon::OutlinedChevronUp->value => 'Chevron Up',
            Heroicon::OutlinedChevronUpDown->value => 'Chevron Up Down',
            Heroicon::OutlinedCircleStack->value => 'Circle Stack',
            Heroicon::OutlinedClipboard->value => 'Clipboard',
            Heroicon::OutlinedClipboardDocument->value => 'Clipboard Document',
            Heroicon::OutlinedClipboardDocumentCheck->value => 'Clipboard Document Check',
            Heroicon::OutlinedClipboardDocumentList->value => 'Clipboard Document List',
            Heroicon::OutlinedClock->value => 'Clock',
            Heroicon::OutlinedCloud->value => 'Cloud',
            Heroicon::OutlinedCloudArrowDown->value => 'Cloud Arrow Down',
            Heroicon::OutlinedCloudArrowUp->value => 'Cloud Arrow Up',
            Heroicon::OutlinedCodeBracket->value => 'Code Bracket',
            Heroicon::OutlinedCodeBracketSquare->value => 'Code Bracket Square',
            Heroicon::OutlinedCog->value => 'Cog',
            Heroicon::OutlinedCog6Tooth->value => 'Cog 6 Tooth',
            Heroicon::OutlinedCog8Tooth->value => 'Cog 8 Tooth',
            Heroicon::OutlinedCommandLine->value => 'Command Line',
            Heroicon::OutlinedComputerDesktop->value => 'Computer Desktop',
            Heroicon::OutlinedCpuChip->value => 'CPU Chip',
            Heroicon::OutlinedCreditCard->value => 'Credit Card',
            Heroicon::OutlinedCube->value => 'Cube',
            Heroicon::OutlinedCubeTransparent->value => 'Cube Transparent',
            Heroicon::OutlinedCurrencyBangladeshi->value => 'Currency Bangladeshi',
            Heroicon::OutlinedCurrencyDollar->value => 'Currency Dollar',
            Heroicon::OutlinedCurrencyEuro->value => 'Currency Euro',
            Heroicon::OutlinedCurrencyPound->value => 'Currency Pound',
            Heroicon::OutlinedCurrencyRupee->value => 'Currency Rupee',
            Heroicon::OutlinedCurrencyYen->value => 'Currency Yen',
            Heroicon::OutlinedCursorArrowRays->value => 'Cursor Arrow Rays',
            Heroicon::OutlinedCursorArrowRipple->value => 'Cursor Arrow Ripple',
            Heroicon::OutlinedDevicePhoneMobile->value => 'Device Phone Mobile',
            Heroicon::OutlinedDeviceTablet->value => 'Device Tablet',
            Heroicon::OutlinedDivide->value => 'Divide',
            Heroicon::OutlinedDocument->value => 'Document',
            Heroicon::OutlinedDocumentArrowDown->value => 'Document Arrow Down',
            Heroicon::OutlinedDocumentArrowUp->value => 'Document Arrow Up',
            Heroicon::OutlinedDocumentChartBar->value => 'Document Chart Bar',
            Heroicon::OutlinedDocumentCheck->value => 'Document Check',
            Heroicon::OutlinedDocumentCurrencyBangladeshi->value => 'Document Currency Bangladeshi',
            Heroicon::OutlinedDocumentCurrencyDollar->value => 'Document Currency Dollar',
            Heroicon::OutlinedDocumentCurrencyEuro->value => 'Document Currency Euro',
            Heroicon::OutlinedDocumentCurrencyPound->value => 'Document Currency Pound',
            Heroicon::OutlinedDocumentCurrencyRupee->value => 'Document Currency Rupee',
            Heroicon::OutlinedDocumentCurrencyYen->value => 'Document Currency Yen',
            Heroicon::OutlinedDocumentDuplicate->value => 'Document Duplicate',
            Heroicon::OutlinedDocumentMagnifyingGlass->value => 'Document Magnifying Glass',
            Heroicon::OutlinedDocumentMinus->value => 'Document Minus',
            Heroicon::OutlinedDocumentPlus->value => 'Document Plus',
            Heroicon::OutlinedDocumentText->value => 'Document Text',
            Heroicon::OutlinedEllipsisHorizontal->value => 'Ellipsis Horizontal',
            Heroicon::OutlinedEllipsisHorizontalCircle->value => 'Ellipsis Horizontal Circle',
            Heroicon::OutlinedEllipsisVertical->value => 'Ellipsis Vertical',
            Heroicon::OutlinedEnvelope->value => 'Envelope',
            Heroicon::OutlinedEnvelopeOpen->value => 'Envelope Open',
            Heroicon::OutlinedEquals->value => 'Equals',
            Heroicon::OutlinedExclamationCircle->value => 'Exclamation Circle',
            Heroicon::OutlinedExclamationTriangle->value => 'Exclamation Triangle',
            Heroicon::OutlinedEye->value => 'Eye',
            Heroicon::OutlinedEyeDropper->value => 'Eye Dropper',
            Heroicon::OutlinedEyeSlash->value => 'Eye Slash',
            Heroicon::OutlinedFaceFrown->value => 'Face Frown',
            Heroicon::OutlinedFaceSmile->value => 'Face Smile',
            Heroicon::OutlinedFilm->value => 'Film',
            Heroicon::OutlinedFingerPrint->value => 'Fingerprint',
            Heroicon::OutlinedFire->value => 'Fire',
            Heroicon::OutlinedFlag->value => 'Flag',
            Heroicon::OutlinedFolder->value => 'Folder',
            Heroicon::OutlinedFolderArrowDown->value => 'Folder Arrow Down',
            Heroicon::OutlinedFolderMinus->value => 'Folder Minus',
            Heroicon::OutlinedFolderOpen->value => 'Folder Open',
            Heroicon::OutlinedFolderPlus->value => 'Folder Plus',
            Heroicon::OutlinedForward->value => 'Forward',
            Heroicon::OutlinedFunnel->value => 'Funnel',
            Heroicon::OutlinedGif->value => 'GIF',
            Heroicon::OutlinedGift->value => 'Gift',
            Heroicon::OutlinedGiftTop->value => 'Gift Top',
            Heroicon::OutlinedGlobeAlt->value => 'Globe Alt',
            Heroicon::OutlinedGlobeAmericas->value => 'Globe Americas',
            Heroicon::OutlinedGlobeAsiaAustralia->value => 'Globe Asia Australia',
            Heroicon::OutlinedGlobeEuropeAfrica->value => 'Globe Europe Africa',
            Heroicon::OutlinedH1->value => 'H1',
            Heroicon::OutlinedH2->value => 'H2',
            Heroicon::OutlinedH3->value => 'H3',
            Heroicon::OutlinedHandRaised->value => 'Hand Raised',
            Heroicon::OutlinedHandThumbDown->value => 'Hand Thumb Down',
            Heroicon::OutlinedHandThumbUp->value => 'Hand Thumb Up',
            Heroicon::OutlinedHashtag->value => 'Hashtag',
            Heroicon::OutlinedHeart->value => 'Heart',
            Heroicon::OutlinedHome->value => 'Home',
            Heroicon::OutlinedHomeModern->value => 'Home Modern',
            Heroicon::OutlinedIdentification->value => 'Identification',
            Heroicon::OutlinedInbox->value => 'Inbox',
            Heroicon::OutlinedInboxArrowDown->value => 'Inbox Arrow Down',
            Heroicon::OutlinedInboxStack->value => 'Inbox Stack',
            Heroicon::OutlinedInformationCircle->value => 'Information Circle',
            Heroicon::OutlinedItalic->value => 'Italic',
            Heroicon::OutlinedKey->value => 'Key',
            Heroicon::OutlinedLanguage->value => 'Language',
            Heroicon::OutlinedLifebuoy->value => 'Lifebuoy',
            Heroicon::OutlinedLightBulb->value => 'Light Bulb',
            Heroicon::OutlinedLink->value => 'Link',
            Heroicon::OutlinedLinkSlash->value => 'Link Slash',
            Heroicon::OutlinedListBullet->value => 'List Bullet',
            Heroicon::OutlinedLockClosed->value => 'Lock Closed',
            Heroicon::OutlinedLockOpen->value => 'Lock Open',
            Heroicon::OutlinedMagnifyingGlass->value => 'Magnifying Glass',
            Heroicon::OutlinedMagnifyingGlassCircle->value => 'Magnifying Glass Circle',
            Heroicon::OutlinedMagnifyingGlassMinus->value => 'Magnifying Glass Minus',
            Heroicon::OutlinedMagnifyingGlassPlus->value => 'Magnifying Glass Plus',
            Heroicon::OutlinedMap->value => 'Map',
            Heroicon::OutlinedMapPin->value => 'Map Pin',
            Heroicon::OutlinedMegaphone->value => 'Megaphone',
            Heroicon::OutlinedMicrophone->value => 'Microphone',
            Heroicon::OutlinedMinus->value => 'Minus',
            Heroicon::OutlinedMinusCircle->value => 'Minus Circle',
            Heroicon::OutlinedMinusSmall->value => 'Minus Small',
            Heroicon::OutlinedMoon->value => 'Moon',
            Heroicon::OutlinedMusicalNote->value => 'Musical Note',
            Heroicon::OutlinedNewspaper->value => 'Newspaper',
            Heroicon::OutlinedNoSymbol->value => 'No Symbol',
            Heroicon::OutlinedNumberedList->value => 'Numbered List',
            Heroicon::OutlinedPaintBrush->value => 'Paint Brush',
            Heroicon::OutlinedPaperAirplane->value => 'Paper Airplane',
            Heroicon::OutlinedPaperClip->value => 'Paper Clip',
            Heroicon::OutlinedPause->value => 'Pause',
            Heroicon::OutlinedPauseCircle->value => 'Pause Circle',
            Heroicon::OutlinedPencil->value => 'Pencil',
            Heroicon::OutlinedPencilSquare->value => 'Pencil Square',
            Heroicon::OutlinedPercentBadge->value => 'Percent Badge',
            Heroicon::OutlinedPhone->value => 'Phone',
            Heroicon::OutlinedPhoneArrowDownLeft->value => 'Phone Arrow Down Left',
            Heroicon::OutlinedPhoneArrowUpRight->value => 'Phone Arrow Up Right',
            Heroicon::OutlinedPhoneXMark->value => 'Phone X Mark',
            Heroicon::OutlinedPhoto->value => 'Photo',
            Heroicon::OutlinedPlay->value => 'Play',
            Heroicon::OutlinedPlayCircle->value => 'Play Circle',
            Heroicon::OutlinedPlayPause->value => 'Play Pause',
            Heroicon::OutlinedPlus->value => 'Plus',
            Heroicon::OutlinedPlusCircle->value => 'Plus Circle',
            Heroicon::OutlinedPlusSmall->value => 'Plus Small',
            Heroicon::OutlinedPower->value => 'Power',
            Heroicon::OutlinedPresentationChartBar->value => 'Presentation Chart Bar',
            Heroicon::OutlinedPresentationChartLine->value => 'Presentation Chart Line',
            Heroicon::OutlinedPrinter->value => 'Printer',
            Heroicon::OutlinedPuzzlePiece->value => 'Puzzle Piece',
            Heroicon::OutlinedQrCode->value => 'QR Code',
            Heroicon::OutlinedQuestionMarkCircle->value => 'Question Mark Circle',
            Heroicon::OutlinedQueueList->value => 'Queue List',
            Heroicon::OutlinedRadio->value => 'Radio',
            Heroicon::OutlinedReceiptPercent->value => 'Receipt Percent',
            Heroicon::OutlinedReceiptRefund->value => 'Receipt Refund',
            Heroicon::OutlinedRectangleGroup->value => 'Rectangle Group',
            Heroicon::OutlinedRectangleStack->value => 'Rectangle Stack',
            Heroicon::OutlinedRocketLaunch->value => 'Rocket Launch',
            Heroicon::OutlinedRss->value => 'RSS',
            Heroicon::OutlinedScale->value => 'Scale',
            Heroicon::OutlinedScissors->value => 'Scissors',
            Heroicon::OutlinedServer->value => 'Server',
            Heroicon::OutlinedServerStack->value => 'Server Stack',
            Heroicon::OutlinedShare->value => 'Share',
            Heroicon::OutlinedShieldCheck->value => 'Shield Check',
            Heroicon::OutlinedShieldExclamation->value => 'Shield Exclamation',
            Heroicon::OutlinedShoppingBag->value => 'Shopping Bag',
            Heroicon::OutlinedShoppingCart->value => 'Shopping Cart',
            Heroicon::OutlinedSignal->value => 'Signal',
            Heroicon::OutlinedSignalSlash->value => 'Signal Slash',
            Heroicon::OutlinedSlash->value => 'Slash',
            Heroicon::OutlinedSparkles->value => 'Sparkles',
            Heroicon::OutlinedSpeakerWave->value => 'Speaker Wave',
            Heroicon::OutlinedSpeakerXMark->value => 'Speaker X Mark',
            Heroicon::OutlinedSquare2Stack->value => 'Square 2 Stack',
            Heroicon::OutlinedSquare3Stack3d->value => 'Square 3 Stack 3D',
            Heroicon::OutlinedSquares2x2->value => 'Squares 2x2',
            Heroicon::OutlinedSquaresPlus->value => 'Squares Plus',
            Heroicon::OutlinedStar->value => 'Star',
            Heroicon::OutlinedStop->value => 'Stop',
            Heroicon::OutlinedStopCircle->value => 'Stop Circle',
            Heroicon::OutlinedStrikethrough->value => 'Strikethrough',
            Heroicon::OutlinedSun->value => 'Sun',
            Heroicon::OutlinedSwatch->value => 'Swatch',
            Heroicon::OutlinedTableCells->value => 'Table Cells',
            Heroicon::OutlinedTag->value => 'Tag',
            Heroicon::OutlinedTicket->value => 'Ticket',
            Heroicon::OutlinedTrash->value => 'Trash',
            Heroicon::OutlinedTrophy->value => 'Trophy',
            Heroicon::OutlinedTruck->value => 'Truck',
            Heroicon::OutlinedTv->value => 'TV',
            Heroicon::OutlinedUnderline->value => 'Underline',
            Heroicon::OutlinedUser->value => 'User',
            Heroicon::OutlinedUserCircle->value => 'User Circle',
            Heroicon::OutlinedUserGroup->value => 'User Group',
            Heroicon::OutlinedUserMinus->value => 'User Minus',
            Heroicon::OutlinedUserPlus->value => 'User Plus',
            Heroicon::OutlinedUsers->value => 'Users',
            Heroicon::OutlinedVariable->value => 'Variable',
            Heroicon::OutlinedVideoCamera->value => 'Video Camera',
            Heroicon::OutlinedVideoCameraSlash->value => 'Video Camera Slash',
            Heroicon::OutlinedViewColumns->value => 'View Columns',
            Heroicon::OutlinedViewfinderCircle->value => 'Viewfinder Circle',
            Heroicon::OutlinedWallet->value => 'Wallet',
            Heroicon::OutlinedWifi->value => 'WiFi',
            Heroicon::OutlinedWindow->value => 'Window',
            Heroicon::OutlinedWrench->value => 'Wrench',
            Heroicon::OutlinedWrenchScrewdriver->value => 'Wrench Screwdriver',
            Heroicon::OutlinedXCircle->value => 'X Circle',
            Heroicon::OutlinedXMark->value => 'X Mark',
        ];
    }
}
